/**
 * ACI 318 compliant Strip Footing Design Engine
 * Designed by Senior Structural Foundation Software Engineer
 * 
 * This module performs ultimate strength design of continuous/strip footings supporting columns or walls,
 * consuming results generated by the Strip Footing Analysis Engine.
 */

import { StripFootingAnalysisResult, StripFootingNodeResult, CriticalSection } from './stripFootingEngine';

export interface RebarDetails {
  diameter: number;         // mm (e.g., 16, 20)
  quantity: number;         // total count across B width (for longitudinal) or spaced along L (for transverse)
  spacing: number;          // mm center-to-center
  AsRequired: number;       // mm² total
  AsProvided: number;       // mm² total
  length: number;           // mm (length of each bar)
  weightKg: number;         // total steel weight of these bars
  requiresHook: boolean;    // is hook needed based on development length
  ld: number;               // tension development length (mm)
  ldh: number;              // hook development length (mm)
  availableLength: number;  // available length from critical section to footing edge (mm)
}

export interface ReinforcementZone {
  id: string;
  name: string;             // e.g., "Left Cantilever", "Span 1 (C1-C2)", "Under Column C1"
  startCoord: number;       // m from left end
  endCoord: number;         // m from left end
  length: number;           // m
  
  // Design values
  governingMuNeg: number;   // kN·m (tension on top, negative)
  governingMuPos: number;   // kN·m (tension on bottom, positive)
  
  // Provided Reinforcement
  topRebar: RebarDetails;
  bottomRebar: RebarDetails;
  
  // Status check
  isTopSafe: boolean;
  isBottomSafe: boolean;
}

export interface TransverseDesign {
  cantileverLength: number; // mm
  governingPressure: number;// kN/m²
  MuTransverse: number;     // kN·m/m
  AsRequiredPerMeter: number; // mm²/m
  AsMinPerMeter: number;    // mm²/m
  governingType: 'strength' | 'minimum';
  selectedDiameter: number; // mm
  selectedSpacing: number;  // mm
  AsProvidedPerMeter: number; // mm²/m
  totalQuantity: number;    // total number of transverse bars along length L
  barLength: number;        // mm
  totalWeightKg: number;    // total weight of all transverse bars
  rebarDetails: RebarDetails;
}

export interface OneWayShearCheck {
  x: number;                // location (m)
  label: string;            // structural section description
  Vu: number;               // ultimate shear force (kN)
  Vc: number;               // concrete shear strength (kN)
  phiVc: number;            // factored concrete shear strength (kN)
  dcr: number;              // demand-capacity ratio (Vu / phiVc)
  isSafe: boolean;
}

export interface bearingCheckResult {
  qMaxService: number;      // kN/m²
  qAll: number;             // kN/m²
  dcr: number;              // qMax / qAll
  isSafe: boolean;
}

export interface ThicknessCheckResult {
  H: number;                // mm
  Hmin: number;             // mm (ACI minimum requirements)
  isSafe: boolean;
  status: 'pass' | 'fail';
  reason: string;
}

export interface StripFootingDesignOutput {
  input: {
    L: number;              // mm
    B: number;              // mm
    H: number;              // mm
    fc: number;             // MPa
    fy: number;             // MPa
    cover: number;          // mm
  };
  zones: ReinforcementZone[];
  transverse: TransverseDesign;
  oneWayShear: {
    checks: OneWayShearCheck[];
    maxDCR: number;
    isSafe: boolean;
  };
  bearing: bearingCheckResult;
  thickness: ThicknessCheckResult;
  
  // Material quantities
  concreteVolumeM3: number;
  totalSteelWeightKg: number;
  longitudinalSteelWeightKg: number;
  transverseSteelWeightKg: number;
  overallSteelRatio: number; // kg/m³
  
  warnings: string[];
}

/**
 * Solves for the required reinforcing area of a rectangular concrete flexural member
 * under design bending moment Mu (kN·m), width b (mm), depth d (mm).
 * Returns the required As in mm².
 */
export function calculateAsRequired(
  Mu: number, // kN·m
  b: number,  // mm
  d: number,  // mm
  fc: number, // MPa
  fy: number, // MPa
  phi: number = 0.90
): { As: number; isOversized: boolean } {
  if (Math.abs(Mu) <= 1e-3) {
    return { As: 0, isOversized: false };
  }
  
  // Convert Mu to N·mm
  const MuNmm = Math.abs(Mu) * 1e6;
  
  // Coeff Rn
  const Rn = MuNmm / (phi * b * d * d);
  
  // Limit to prevent compression failure (over-reinforced section)
  // For standard Grade 60 rebar and fc' of 25-35 MPa, maximum reinforcement ratio is about 0.015 - 0.02
  // If Rn is greater than typical limit, the section is oversized (requires greater H)
  const limitRn = 0.85 * fc * 0.375 * (1 - 0.5 * 0.375); // rough balance threshold
  if (Rn > limitRn) {
    return { As: (Rn * b * d) / fy, isOversized: true };
  }
  
  const term = 1 - (2 * Rn) / (0.85 * fc);
  if (term < 0) {
    return { As: 0, isOversized: true }; // square root of negative number
  }
  
  const rho = (0.85 * fc / fy) * (1 - Math.sqrt(term));
  const As = rho * b * d;
  
  return { As, isOversized: false };
}

/**
 * Computes tension development length Ld (mm) for straight deformed bars
 * and Ldh (mm) for standard 90-degree hooks in tension as per ACI 318 Chapter 25.
 */
export function calculateDevelopmentLength(
  db: number,        // mm
  fc: number,        // MPa
  fy: number,        // MPa
  isTopBar: boolean, // top bars cast with more than 300mm concrete below
  cover: number = 75
): { ld: number; ldh: number } {
  // Casting factor psi_t
  const psi_t = isTopBar ? 1.3 : 1.0;
  // Epoxy factor psi_e (assume uncoated)
  const psi_e = 1.0;
  // Size factor psi_s (0.8 for db <= 16mm, 1.0 for db > 16mm)
  const psi_s = db <= 16 ? 0.8 : 1.0;
  // Lightweight factor lambda
  const lambda = 1.0;
  
  // Basic Simplified straight development length formula (assuming clear spacing/cover governs)
  // Ld = (fy * psi_t * psi_e * psi_s) / (2.1 * lambda * sqrt(fc)) * db  (for smaller bars)
  const sqrt_fc = Math.max(1.0, Math.sqrt(fc));
  let ld = 0;
  if (db <= 19) {
    ld = ((fy * psi_t * psi_e * psi_s) / (2.1 * lambda * sqrt_fc)) * db;
  } else {
    ld = ((fy * psi_t * psi_e * psi_s) / (1.7 * lambda * sqrt_fc)) * db;
  }
  
  // Enforce ACI absolute minimum Ld of 300 mm
  ld = Math.max(300, ld);
  
  // 90-degree hook development length Ldh (ACI 25.4.3)
  // Ldh = (fy * psi_e * psi_c * psi_r) / (50 * lambda * sqrt(fc)) * db^1.5 or simplified:
  // Ldh = 0.24 * (fy * psi_e * psi_r) / (lambda * sqrt(fc)) * db  (for Grade 60 (420))
  // ACI 318-19: Ldh = (fy * psi_e * psi_c * psi_r) / (2.1 * lambda * sqrt(fc)) * db^1.5 (English)
  // Metric simple standard: Ldh = (0.24 * d_b * (fy / sqrt(fc')) * factors)
  let ldh = (0.24 * db * (fy / sqrt_fc));
  // Apply modification factor for cover (0.7 if side cover >= 60mm and hook cover >= 50mm)
  if (cover >= 60) {
    ldh = ldh * 0.7;
  }
  // Enforce absolute minimum Ldh of 150 mm or 8*db
  ldh = Math.max(150, 8 * db, ldh);
  
  return {
    ld: Math.round(ld),
    ldh: Math.round(ldh)
  };
}

/**
 * Helper to automatically select the optimal combination of bar diameter, reinforcement spacing,
 * and bar quantity to satisfy target required reinforcing area AsRequired (mm²) across a given width b (mm).
 * Respects maximum spacing limitations (minor of 450 mm or 3H for temperature, 300 mm or 2H for strength).
 */
export function selectReinforcementLayout(
  AsRequired: number,
  width: number,      // mm
  H: number,          // mm
  cover: number = 75,
  preferredBarDia: number = 16,
  isMainFlexure: boolean = true
): { diameter: number; quantity: number; spacing: number; AsProvided: number } {
  // Candidate diameters
  const diameters = [12, 14, 16, 18, 20, 22, 25, 28, 32];
  
  // Find index of preferred diameter
  let targetDia = preferredBarDia;
  if (!diameters.includes(targetDia)) {
    targetDia = 16;
  }
  
  // Limits on spacing
  const maxSpacing = isMainFlexure 
    ? Math.min(300, 2 * H) 
    : Math.min(450, 3 * H);
  
  const minSpacing = Math.max(50, 1.5 * targetDia, 40); // practical clearance limit
  
  const selectForDia = (d: number) => {
    const areaSingle = (Math.PI * d * d) / 4;
    // Calculate raw required quantity
    let qty = Math.ceil(AsRequired / areaSingle);
    
    // Minimum quantity (e.g., at least 3 longitudinal bars in a strip width)
    if (isMainFlexure) {
      qty = Math.max(qty, 3);
    } else {
      qty = Math.max(qty, 2);
    }
    
    // Spacing
    let spacing = qty > 1 ? (width - 2 * cover - d) / (qty - 1) : maxSpacing;
    
    // If spacing exceeds max spacing, increase quantity to meet spacing criteria
    if (spacing > maxSpacing) {
      spacing = maxSpacing;
      qty = Math.ceil((width - 2 * cover - d) / spacing) + 1;
    }
    
    // If spacing is smaller than minSpacing, we must check if we should escalate quantity or notify
    const AsProvided = qty * areaSingle;
    return { diameter: d, quantity: qty, spacing: Math.round(spacing), AsProvided };
  };
  
  // Try preferred diameter first
  let result = selectForDia(targetDia);
  
  // If the preferred diameter's spacing is too dense (< 75mm), scale up the bar diameter
  if (result.spacing < 75 && targetDia !== 32) {
    for (const d of diameters) {
      if (d > targetDia) {
        const altResult = selectForDia(d);
        if (altResult.spacing >= 75) {
          result = altResult;
          break;
        }
      }
    }
  }
  
  return result;
}

/**
 * Solves the ultimate limit state design of a Strip Footing based on ACI 318
 */
export function designStripFootingStrength(
  analysis: StripFootingAnalysisResult,
  preferredLongDia: number = 16,
  preferredTransDia: number = 16,
  cover: number = 75
): StripFootingDesignOutput {
  const { L, B, H, fc, fy, qall } = analysis.input;
  const warnings: string[] = [];
  
  const L_m = L / 1000;
  const B_m = B / 1000;
  const H_m = H / 1000;
  
  // Factored reduction factors
  const phiFlexure = 0.90;
  const phiShear = 0.75;
  
  // Concrete parameters
  const concreteVolumeM3 = B_m * L_m * H_m;
  
  // Effective depths
  // Longitudinal reinforcement (as continuous beam, bottom outer layer, top outer layer)
  const d_long = H - cover - preferredLongDia / 2; // mm
  // Transverse reinforcement sits on top of longitudinal
  const d_trans = d_long - preferredLongDia / 2 - preferredTransDia / 2; // mm
  
  // Standard minimum reinforcement criteria (ACI 318-19 Section 7.6.1.1 / 8.6.1.1)
  // Shrinkage & Temperature: As_min = 0.0018 * Ag
  const Ag_long = B * H; // total cross section of strip (B x H)
  const AsMinLongTotal = 0.0018 * Ag_long; // mm² over total width B
  
  // For flexure (ACI 318-19 Section 9.6.1.2) - minimum flexural reinforce for beams
  const AsMinFlexureLong = Math.max(
    (0.25 * Math.sqrt(fc) * B * d_long) / fy,
    (1.4 * B * d_long) / fy
  );
  
  // The governing minimum longitudinal reinforcement area over total width B
  const AsMinLongGoverning = Math.max(AsMinLongTotal, AsMinFlexureLong);
  
  // Prepare discrete longitudinal reinforcement zones along footing length
  // We can group nodes and identify critical positive/negative spans
  const columns = analysis.input.loads.filter(l => l.type === 'column' || l.type === 'point');
  
  // Partition footing into segments: Cantilever left (if any), Supports, Midspans, Cantilever right (if any)
  // To keep it robust, let's sort columns by coordinate
  const sortedColumns = [...columns].sort((a, b) => a.x - b.x);
  
  interface ZoneBoundary {
    id: string;
    name: string;
    start: number;
    end: number;
  }
  
  const rawBoundaries: ZoneBoundary[] = [];
  
  if (sortedColumns.length === 0) {
    // If no columns are defined, treat entire footing as one uniform zone
    rawBoundaries.push({ id: 'zone-all', name: 'كامل امتداد الأساس (Uniform Zone)', start: 0, end: L_m });
  } else {
    // Left cantilever
    const firstCol = sortedColumns[0];
    const firstFaceLeft = firstCol.x - (firstCol.columnCx ?? 300) / 2000;
    if (firstFaceLeft > 0.1) {
      rawBoundaries.push({
        id: 'zone-cant-left',
        name: 'كابولي أيسر (Left Cantilever)',
        start: 0,
        end: parseFloat(firstFaceLeft.toFixed(3))
      });
    }
    
    // Intercolumn supports and spans
    for (let i = 0; i < sortedColumns.length; i++) {
      const col = sortedColumns[i];
      const cx_m = (col.columnCx ?? 300) / 1000;
      const colStart = Math.max(0, col.x - cx_m / 2);
      const colEnd = Math.min(L_m, col.x + cx_m / 2);
      
      rawBoundaries.push({
        id: `zone-col-${col.id}`,
        name: `دعامة العمود ${col.label} (Support Zone)`,
        start: parseFloat(colStart.toFixed(3)),
        end: parseFloat(colEnd.toFixed(3))
      });
      
      // If there is a next column, add a midspan zone
      if (i < sortedColumns.length - 1) {
        const nextCol = sortedColumns[i + 1];
        const nextCx_m = (nextCol.columnCx ?? 300) / 1000;
        const spanStart = colEnd;
        const spanEnd = Math.max(spanStart, nextCol.x - nextCx_m / 2);
        
        if (spanEnd > spanStart + 0.1) {
          rawBoundaries.push({
            id: `zone-span-${col.id}-${nextCol.id}`,
            name: `بحر بين العمودين ${col.label} و ${nextCol.label} (Midspan Zone)`,
            start: parseFloat(spanStart.toFixed(3)),
            end: parseFloat(spanEnd.toFixed(3))
          });
        }
      }
    }
    
    // Right cantilever
    const lastCol = sortedColumns[sortedColumns.length - 1];
    const lastFaceRight = lastCol.x + (lastCol.columnCx ?? 300) / 2000;
    if (L_m - lastFaceRight > 0.1) {
      rawBoundaries.push({
        id: 'zone-cant-right',
        name: 'كابولي أيمن (Right Cantilever)',
        start: parseFloat(lastFaceRight.toFixed(3)),
        end: L_m
      });
    }
  }
  
  // Map ultimate analysis nodes to each zone to find peak positive/negative moments
  const zones: ReinforcementZone[] = rawBoundaries.map((b, zIdx) => {
    // Gather ultimate combination nodes inside this zone boundaries
    const zoneNodes = analysis.combinations.ultimate.nodes.filter(
      n => n.x >= b.start - 1e-4 && n.x <= b.end + 1e-4
    );
    
    let maxMuPos = 0; // Bottom fiber tension
    let maxMuNeg = 0; // Top fiber tension (represented as negative)
    
    zoneNodes.forEach(node => {
      if (node.moment > maxMuPos) {
        maxMuPos = node.moment;
      }
      if (node.moment < maxMuNeg) {
        maxMuNeg = node.moment; // negative value
      }
    });
    
    // Calculate required areas (Mu is in kN·m for the entire width B)
    const topAsCalc = calculateAsRequired(Math.abs(maxMuNeg), B, d_long, fc, fy, phiFlexure);
    const botAsCalc = calculateAsRequired(maxMuPos, B, d_long, fc, fy, phiFlexure);
    
    if (topAsCalc.isOversized) {
      warnings.push(`تحذير متطلبات التسليح العلوي في ${b.name}: العزم السالب الأقصى (${Math.abs(maxMuNeg).toFixed(1)} kN·m) يتخطى الحد الأقصى للمقطع الخرساني الحالي. يرجى زيادة سمك الصبة H.`);
    }
    if (botAsCalc.isOversized) {
      warnings.push(`تحذير متطلبات التسليح السفلي في ${b.name}: العزم الموجب الأقصى (${maxMuPos.toFixed(1)} kN·m) يتخطى الحد الأقصى للمقطع الخرساني الحالي. يرجى زيادة سمك الصبة H.`);
    }
    
    // Apply ACI Minimum Reinforcement criteria:
    // If required area is less than minimum, use minimum steel
    // But as per ACI 318 9.6.1.3, if AsRequired * 1.33 is smaller than minimum, we can use 1.33 * AsRequired
    const applyMinFlexure = (asReq: number) => {
      if (asReq <= 1e-3) {
        // even if zero moment, we must provide temperature/shrinkage minimum
        return AsMinLongTotal; 
      }
      const potentialMin = AsMinLongGoverning;
      if (asReq < potentialMin) {
        const altMin = asReq * 1.33;
        const governedMin = Math.min(potentialMin, altMin);
        // It should never be less than temperature-shrinkage minimum
        return Math.max(governedMin, AsMinLongTotal);
      }
      return asReq;
    };
    
    const topAsRequired = applyMinFlexure(topAsCalc.As);
    const botAsRequired = applyMinFlexure(botAsCalc.As);
    
    // Reinforcement Selection for Top and Bottom layers
    // For Top (under columns, negative moment governs, bar lengths are extended)
    const topLayout = selectReinforcementLayout(topAsRequired, B, H, cover, preferredLongDia, true);
    // For Bottom (midspans, positive moment governs)
    const botLayout = selectReinforcementLayout(botAsRequired, B, H, cover, preferredLongDia, true);
    
    // Development Length and hooks calculations for this zone
    // Straight development length Ld
    const topDev = calculateDevelopmentLength(topLayout.diameter, fc, fy, true, cover);
    const botDev = calculateDevelopmentLength(botLayout.diameter, fc, fy, false, cover);
    
    // Calculate available length for cantilever or support termination
    // For cantilever zones, available length is from the column face to edge minus cover
    let topAvailable = 10000;
    let botAvailable = 10000;
    let topRequiresHook = false;
    let botRequiresHook = false;
    
    const zoneLengthMM = (b.end - b.start) * 1000;
    
    if (b.id === 'zone-cant-left' || b.id === 'zone-cant-right') {
      // In cantilevers, the bars must develop from the face of the column to the free end
      const availableDevLen = zoneLengthMM - cover;
      topAvailable = availableDevLen;
      botAvailable = availableDevLen;
      
      if (availableDevLen < topDev.ld && Math.abs(maxMuNeg) > 5) {
        topRequiresHook = true;
      }
      if (availableDevLen < botDev.ld && maxMuPos > 5) {
        botRequiresHook = true;
      }
    }
    
    // Bar Weight metrics: Weight = quantity * length * weight/meter
    const densitySteel = 7850; // kg/m³
    const barWeightPerMeter = (layout: typeof topLayout) => {
      return (Math.PI * layout.diameter * layout.diameter / 4) * 1e-6 * densitySteel; // kg/m
    };
    
    const zoneLenM = b.end - b.start;
    const barLenMM = zoneLenM * 1000; // bar length in mm is the zone length
    
    const topWeightKg = topLayout.quantity * (barLenMM / 1000) * barWeightPerMeter(topLayout);
    const botWeightKg = botLayout.quantity * (barLenMM / 1000) * barWeightPerMeter(botLayout);
    
    return {
      id: b.id,
      name: b.name,
      startCoord: b.start,
      endCoord: b.end,
      length: parseFloat(zoneLenM.toFixed(3)),
      governingMuNeg: parseFloat(maxMuNeg.toFixed(2)),
      governingMuPos: parseFloat(maxMuPos.toFixed(2)),
      topRebar: {
        diameter: topLayout.diameter,
        quantity: topLayout.quantity,
        spacing: topLayout.spacing,
        AsRequired: parseFloat(topAsRequired.toFixed(1)),
        AsProvided: parseFloat(topLayout.AsProvided.toFixed(1)),
        length: Math.round(barLenMM),
        weightKg: parseFloat(topWeightKg.toFixed(2)),
        requiresHook: topRequiresHook,
        ld: topDev.ld,
        ldh: topDev.ldh,
        availableLength: Math.round(topAvailable)
      },
      bottomRebar: {
        diameter: botLayout.diameter,
        quantity: botLayout.quantity,
        spacing: botLayout.spacing,
        AsRequired: parseFloat(botAsRequired.toFixed(1)),
        AsProvided: parseFloat(botLayout.AsProvided.toFixed(1)),
        length: Math.round(barLenMM),
        weightKg: parseFloat(botWeightKg.toFixed(2)),
        requiresHook: botRequiresHook,
        ld: botDev.ld,
        ldh: botDev.ldh,
        availableLength: Math.round(botAvailable)
      },
      isTopSafe: topLayout.AsProvided >= topAsRequired,
      isBottomSafe: botLayout.AsProvided >= botAsRequired
    };
  });
  
  // --- 2. TRANSVERSE CANTILEVER FLEXURE DESIGN ---
  // The footing width B acts as a double cantilever in the transverse direction.
  // We assume columns have average dimension Cy transverse to length. Let's find columns' Cy:
  const colCys = columns.map(c => c.columnCy ?? 300);
  const avgCy = colCys.length > 0 ? colCys.reduce((sum, val) => sum + val, 0) / colCys.length : 300;
  
  // Transverse cantilever length (mm)
  const transverseCantLengthMM = Math.max(100, (B - avgCy) / 2);
  const transCant_m = transverseCantLengthMM / 1000;
  
  // Governing soil pressure under columns or max ultimate pressure
  const peakSoilPressureUltimate = analysis.combinations.ultimate.maxPressure; // kN/m²
  
  // Design Transverse Moment per meter length of footing at the support face:
  // Mu_trans = q_u * L_cant^2 / 2 (kN·m/m)
  const MuTransverse = peakSoilPressureUltimate * transCant_m * transCant_m / 2; // kN·m/m
  
  // Design transverse reinforcing steel (per meter length, b = 1000 mm)
  const transAsCalc = calculateAsRequired(MuTransverse, 1000, d_trans, fc, fy, phiFlexure);
  
  // Transverse minimum reinforcement is shrinkage-temperature:
  // As_min_trans = 0.0018 * 1000 * H (mm²/m)
  const AsMinTransPerMeter = 0.0018 * 1000 * H;
  
  // Code minimum or 1.33 * strength required
  let governingType: 'strength' | 'minimum' = 'strength';
  let transAsRequired = transAsCalc.As;
  if (transAsRequired < AsMinTransPerMeter) {
    governingType = 'minimum';
    const altMin = transAsRequired * 1.33;
    transAsRequired = Math.max(AsMinTransPerMeter, altMin);
  }
  
  // Select concrete reinforcing layout for transverse bars
  const transLayout = selectReinforcementLayout(transAsRequired, 1000, H, cover, preferredTransDia, false);
  
  // Determine development length in the transverse cantilever:
  // available length is transCant_m * 1000 - cover (75 mm)
  const transAvailableMM = transverseCantLengthMM - cover;
  const transDev = calculateDevelopmentLength(transLayout.diameter, fc, fy, false, cover);
  const transRequiresHook = transAvailableMM < transDev.ld;
  
  // Total number of transverse bars along entire footing length L:
  // spacing is transLayout.spacing center-to-center.
  // Quantity of transverse bars = Math.ceil(L / spacing) + 1
  const totalTransQty = Math.ceil(L / transLayout.spacing) + 1;
  const transBarLen = B - 2 * cover; // mm (running across width B)
  
  const transBarWeightPerMeter = (Math.PI * transLayout.diameter * transLayout.diameter / 4) * 1e-6 * 7850;
  const transTotalWeightKg = totalTransQty * (transBarLen / 1000) * transBarWeightPerMeter;
  
  const transverseDesign: TransverseDesign = {
    cantileverLength: Math.round(transverseCantLengthMM),
    governingPressure: parseFloat(peakSoilPressureUltimate.toFixed(1)),
    MuTransverse: parseFloat(MuTransverse.toFixed(2)),
    AsRequiredPerMeter: parseFloat(transAsRequired.toFixed(1)),
    AsMinPerMeter: parseFloat(AsMinTransPerMeter.toFixed(1)),
    governingType,
    selectedDiameter: transLayout.diameter,
    selectedSpacing: transLayout.spacing,
    AsProvidedPerMeter: parseFloat(transLayout.AsProvided.toFixed(1)),
    totalQuantity: totalTransQty,
    barLength: Math.round(transBarLen),
    totalWeightKg: parseFloat(transTotalWeightKg.toFixed(2)),
    rebarDetails: {
      diameter: transLayout.diameter,
      quantity: totalTransQty,
      spacing: transLayout.spacing,
      AsRequired: parseFloat(transAsRequired.toFixed(1)),
      AsProvided: parseFloat(transLayout.AsProvided.toFixed(1)),
      length: Math.round(transBarLen),
      weightKg: parseFloat(transTotalWeightKg.toFixed(2)),
      requiresHook: transRequiresHook,
      ld: transDev.ld,
      ldh: transDev.ldh,
      availableLength: Math.round(transAvailableMM)
    }
  };
  
  // --- 3. ONE-WAY SHEAR CHECKS AT CRITICAL SECTIONS ---
  // One-way shear capacity phiVc = phi * 0.17 * sqrt(fc') * B * d
  const Vc_N = 0.17 * Math.sqrt(fc) * B * d_long; // N
  const phiVc = (phiShear * Vc_N) / 1000; // kN
  
  const oneWayShearChecks: OneWayShearCheck[] = [];
  
  // Look through CriticalSections generated by Analysis Engine
  const activeOneWayShearSections = analysis.designRegions.filter(r => r.type === 'one_way_shear_d');
  
  activeOneWayShearSections.forEach(section => {
    const Vu = Math.abs(section.governingValue);
    const dcr = Vu / phiVc;
    const isSafe = Vu <= phiVc;
    
    if (!isSafe) {
      warnings.push(`تحذير تجاوز مقاومة القص أحادي الاتجاه عند المقطع ${section.label}: قوى القص القصوى (${Vu.toFixed(1)} kN) تتجاوز قدرة المقطع المسلح للخرسانة (φVc = ${phiVc.toFixed(1)} kN). يرجى زيادة سمك صبة الأساس H.`);
    }
    
    oneWayShearChecks.push({
      x: section.xStart,
      label: section.label,
      Vu: parseFloat(Vu.toFixed(1)),
      Vc: parseFloat((Vc_N / 1000).toFixed(1)),
      phiVc: parseFloat(phiVc.toFixed(1)),
      dcr: parseFloat(dcr.toFixed(3)),
      isSafe
    });
  });
  
  // If no shear sections were predefined, run a general check at max shear location
  if (oneWayShearChecks.length === 0) {
    const mainMaxV = analysis.combinations.ultimate.maxShear;
    const dcr = mainMaxV / phiVc;
    const isSafe = mainMaxV <= phiVc;
    oneWayShearChecks.push({
      x: analysis.combinations.ultimate.maxShearX,
      label: 'مقطع أكبر قوى قص عام في شريط الأساس',
      Vu: parseFloat(mainMaxV.toFixed(1)),
      Vc: parseFloat((Vc_N / 1000).toFixed(1)),
      phiVc: parseFloat(phiVc.toFixed(1)),
      dcr: parseFloat(dcr.toFixed(3)),
      isSafe
    });
  }
  
  const maxDCRShear = Math.max(...oneWayShearChecks.map(c => c.dcr));
  const isShearSafe = oneWayShearChecks.every(c => c.isSafe);
  
  // --- 4. BEARING CAPACITY VALIDATION ---
  const maxQService = analysis.combinations.service.maxPressure;
  const isBearingSafe = maxQService <= qall;
  const bearingDCR = maxQService / qall;
  
  if (!isBearingSafe) {
    warnings.push(`تعدي إجهاد التربة: ضغط التماس للتربة تحت الأحمال التشغيلية q_max = ${maxQService.toFixed(1)} kN/m² أكبر من قدرة التحمل المسموحة المقررة q_all = ${qall} kN/m². يجب زيادة عرض الأساس B لمنع حدوث غوص أو هبوط تفاضلي.`);
  }
  
  const bearingCheck: bearingCheckResult = {
    qMaxService: parseFloat(maxQService.toFixed(2)),
    qAll: qall,
    dcr: parseFloat(bearingDCR.toFixed(3)),
    isSafe: isBearingSafe
  };
  
  // --- 5. FOOTING THICKNESS ADHERENCE ---
  // ACI prescribes standard structural limits for footings: H_min = 150mm above reinforcing steel,
  // meaning H approx 250mm or 300mm. Also check shear and flexural checks to declare status.
  const Hmin = 250; // standard commercial default for continuous strip footing
  const isThicknessSafe = H >= Hmin && isShearSafe;
  
  let thicknessStatus: 'pass' | 'fail' = 'pass';
  let thicknessReason = 'السمك الخرساني يحقق اشتراطات الكود ومقاومة القص الطولي.';
  
  if (H < Hmin) {
    thicknessStatus = 'fail';
    thicknessReason = `سمك الأساس الخرساني يقل عن الحدود التشغيلية الموصى بها في الكود لحماية حديد التسليح للمنشآت الإنشائية الملامسة للتربة (H_min = ${Hmin} مم).`;
    warnings.push(thicknessReason);
  } else if (!isShearSafe) {
    thicknessStatus = 'fail';
    thicknessReason = 'السمك غير كافٍ لمقاومة قاص الاتجاه الواحد المائل بدون تسليح قاص (Requires larger H).';
  }
  
  // --- 6. QUANTITY INTEGRATIONS ---
  // SUM steel weights
  let longitudinalWeightKg = 0;
  zones.forEach(z => {
    longitudinalWeightKg += z.topRebar.weightKg + z.bottomRebar.weightKg;
  });
  
  const totalSteelWeightKg = longitudinalWeightKg + transverseDesign.totalWeightKg;
  const steelRatio = totalSteelWeightKg / concreteVolumeM3; // kg/m³ (typical foundation is 35 - 75 kg/m³)
  
  if (steelRatio > 150) {
    warnings.push(`كثافة حديد التسليح مرتفعة جداً (${steelRatio.toFixed(1)} kg/м³). يشير ذلك إلى تصميم غير اقتصادي أو مقطع خرساني هزيل، يوصى بزيادة سمك الصبة الإنشائية H لتقليص كميات حديد التسليح.`);
  }
  
  return {
    input: {
      L, B, H, fc, fy, cover
    },
    zones,
    transverse: transverseDesign,
    oneWayShear: {
      checks: oneWayShearChecks,
      maxDCR: parseFloat(maxDCRShear.toFixed(3)),
      isSafe: isShearSafe
    },
    bearing: bearingCheck,
    thickness: {
      H,
      Hmin,
      isSafe: isThicknessSafe,
      status: thicknessStatus,
      reason: thicknessReason
    },
    concreteVolumeM3: parseFloat(concreteVolumeM3.toFixed(3)),
    totalSteelWeightKg: parseFloat(totalSteelWeightKg.toFixed(2)),
    longitudinalSteelWeightKg: parseFloat(longitudinalWeightKg.toFixed(2)),
    transverseSteelWeightKg: parseFloat(transverseDesign.totalWeightKg.toFixed(2)),
    overallSteelRatio: parseFloat(steelRatio.toFixed(2)),
    warnings
  };
}
